import { LawyerPrepSheet } from '../types/legal';

/**
 * Utility to export 1-Page Lawyer Consultation Prep Sheet as printable HTML or Markdown.
 */
export function generatePrepSheetMarkdown(prepSheet: LawyerPrepSheet): string {
  let md = `# LAWYER CONSULTATION PREP SHEET
**Document:** ${prepSheet.documentTitle}  
**Date Generated:** ${prepSheet.generatedDate}  
**Platform:** LexiClear AI (JurisMind AI)  

---

## 1. Executive Brief
${prepSheet.executiveBrief}

---

## 2. High-Priority Legal Risks
`;

  prepSheet.highPriorityRisks.forEach((risk, idx) => {
    md += `
### ${idx + 1}. [${risk.clauseTag}] ${risk.issue}
- **Impact:** ${risk.impact}
- **Proposed Mitigation / Fix:** ${risk.proposedFix}
`;
  });

  md += `
---

## 3. Recommended Questions for Legal Counsel
`;

  prepSheet.questionsForCounsel.forEach((q, idx) => {
    md += `${idx + 1}. ${q}\n`;
  });

  md += `
---

## 4. Suggested Contract Redlines
`;

  prepSheet.suggestedRedlines.forEach((redline) => {
    md += `
#### Clause ${redline.clauseTag}
- **Current Text:** \`${redline.currentText}\`
- **Proposed Redline:** \`${redline.proposedRedline}\`
- **Rationale:** ${redline.rationale}
`;
  });

  md += `
---

## 5. Key Dates & Deadlines
`;

  prepSheet.keyDatesAndDeadlines.forEach((date) => {
    md += `- **${date.label}:** ${date.dateOrTimeframe} _(Action: ${date.actionRequired})_\n`;
  });

  md += `
---
*Disclaimer: Generated by LexiClear AI for informational preparation purposes only. Does not constitute formal legal advice.*
`;

  return md;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/markdown'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function printPrepSheet(prepSheet: LawyerPrepSheet): void {
  const mdContent = generatePrepSheetMarkdown(prepSheet);
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Lawyer Consultation Prep Sheet - ${prepSheet.documentTitle}</title>
        <style>
          body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #1e293b; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
          h2 { color: #0f172a; margin-top: 24px; border-bottom: 1px solid #f1f5f9; padding-bottom: 4px; }
          h3 { color: #dc2626; margin-bottom: 4px; }
          code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
          .footer { margin-top: 40px; pt: 16px; border-top: 1px solid #e2e8f0; font-size: 0.85em; color: #64748b; font-style: italic; }
        </style>
      </head>
      <body>
        <pre style="white-space: pre-wrap; font-family: inherit;">${mdContent}</pre>
        <script>window.onload = function() { window.print(); }</script>
      </body>
    </html>
  `);
  printWindow.document.close();
}
